# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'projects', folder: 'pages', file: 'projects.html'}
- {name: 'blog', folder: 'pages', file: 'sample-posts.html'}
#- {name: 'cv bio etc', folder: 'pages', file: 'documentation.html'}
- {name: 'cv bio etc', folder: 'pages', file: 'about.html'}
- {name: 'contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer

- {icon: 'envelope', link: 'mailto:ag-3d@ya.ru'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: '<<<<<'
  previous_page: '>>>>>'
